# Generated by Django 2.2.24 on 2025-03-19 11:41

from django.db import migrations


def new_building_or_not(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.new_building = flat.construction_year >= 2015
        print(flat.construction_year)
        print(f'Обрабатываем квартиру: {flat.id}, Дата создания: {flat.created_at}, Новый: {flat.new_building}')
        flat.save()


def reverse_new_building_or_not(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(new_building=None)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_flat_new_building'),
    ]

    operations = [migrations.RunPython(new_building_or_not, reverse_new_building_or_not)]
