# Generated by Django 2.2.24 on 2025-03-21 18:40

from django.db import migrations
import phonenumbers


def fill_owner_pure_phone_field(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owner_pure_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')
        if phonenumbers.is_valid_number(flat.owner_pure_phone):
            flat.save()
    

def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Flat.objects.update(owner_pure_phone=None)


class Migration(migrations.Migration):


    dependencies = [
        ('property', '0008_flat_owner_pure_phone'),
    ]

    operations = [migrations.RunPython(fill_owner_pure_phone_field, move_backward)]
