# Generated by Django 2.2.24 on 2025-03-22 10:07

from django.db import migrations


def create_owners_flats(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.all():
        owner, created = Owner.objects.get_or_create(
            full_name=flat.owner,
            phone_number=flat.owners_phonenumber,
            normalized_phone_number=flat.owner_pure_phone)
        owner.flats.add(flat)


def move_backward(apps, schema_editor):
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all():
        owner.flats.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20250322_0238'),
    ]

    operations = [migrations.RunPython(create_owners_flats, move_backward)]
